#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lksctp-tools
Version  : 1.0.18
Release  : 9
URL      : https://github.com/sctp/lksctp-tools/archive/v1.0.18/lksctp-tools-1.0.18.tar.gz
Source0  : https://github.com/sctp/lksctp-tools/archive/v1.0.18/lksctp-tools-1.0.18.tar.gz
Summary  : User-level SCTP API library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: lksctp-tools-bin = %{version}-%{release}
Requires: lksctp-tools-data = %{version}-%{release}
Requires: lksctp-tools-lib = %{version}-%{release}
Requires: lksctp-tools-license = %{version}-%{release}
Requires: lksctp-tools-man = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: 0001-withsctp-use-PACKAGE_VERSION-in-withsctp.h.patch
Patch2: 0002-configure.ac-add-CURRENT-REVISION-and-AGE-for-libsct.patch
Patch3: 0003-build-fix-netinet-sctp.h-not-to-be-installed.patch
Patch4: 0004-build-remove-v4.12-secondary-defines-in-favor-of-HAV.patch
Patch5: 0005-build-fix-probing-for-HAVE_SCTP_SENDV.patch
Patch6: 0006-build-0b0dce7a36fb-actually-belongs-to-v4.19.patch
Patch7: 0007-func_tests-fix-use-of-unitialized-var.patch
Patch8: 0008-Fix-error-errno-typos.patch
Patch9: 0009-withsctp-to-not-reuse-PACKAGE_VERSION-as-lib-version.patch
Patch10: 0010-sctp_recvmsg-man-update.patch
Patch11: 0011-automake-fix-include-dir-for-the-now-autogenerated-h.patch
Patch12: 0012-Use-symvmer-attribute-not-asms-for-symbol-versioning.patch
Patch13: 0013-man-sctp.7-fix-several-typos-and-two-formatting-issu.patch
Patch14: 0014-travis-enable-make-distcheck-check.patch
Patch15: 0015-travis-add-tests-for-building-using-a-build-dir.patch
Patch16: 0016-travis-disable-clang-5.0-test.patch
Patch17: 0017-m4-sctp.m4-make-conpatible-to-autoconf-2.70.patch

%description
This is the lksctp-tools package for Linux Kernel SCTP Reference
Implementation.

%package bin
Summary: bin components for the lksctp-tools package.
Group: Binaries
Requires: lksctp-tools-data = %{version}-%{release}
Requires: lksctp-tools-license = %{version}-%{release}

%description bin
bin components for the lksctp-tools package.


%package data
Summary: data components for the lksctp-tools package.
Group: Data

%description data
data components for the lksctp-tools package.


%package dev
Summary: dev components for the lksctp-tools package.
Group: Development
Requires: lksctp-tools-lib = %{version}-%{release}
Requires: lksctp-tools-bin = %{version}-%{release}
Requires: lksctp-tools-data = %{version}-%{release}
Provides: lksctp-tools-devel = %{version}-%{release}
Requires: lksctp-tools = %{version}-%{release}

%description dev
dev components for the lksctp-tools package.


%package lib
Summary: lib components for the lksctp-tools package.
Group: Libraries
Requires: lksctp-tools-data = %{version}-%{release}
Requires: lksctp-tools-license = %{version}-%{release}

%description lib
lib components for the lksctp-tools package.


%package license
Summary: license components for the lksctp-tools package.
Group: Default

%description license
license components for the lksctp-tools package.


%package man
Summary: man components for the lksctp-tools package.
Group: Default

%description man
man components for the lksctp-tools package.


%prep
%setup -q -n lksctp-tools-1.0.18
cd %{_builddir}/lksctp-tools-1.0.18
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1
%patch15 -p1
%patch16 -p1
%patch17 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614637599
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
find ./src/func_tests -maxdepth 1 -type f -perm /u+x -name 'test_*' -exec {} \;

%install
export SOURCE_DATE_EPOCH=1614637599
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lksctp-tools
cp %{_builddir}/lksctp-tools-1.0.18/COPYING %{buildroot}/usr/share/package-licenses/lksctp-tools/faa78032a41c2bfe6bfd1df72ccd1bb7ab4f7a10
cp %{_builddir}/lksctp-tools-1.0.18/COPYING.lib %{buildroot}/usr/share/package-licenses/lksctp-tools/923576601c6fce213eacfa2c860643114a5bf356
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/checksctp
/usr/bin/sctp_darn
/usr/bin/sctp_status
/usr/bin/sctp_test
/usr/bin/withsctp

%files data
%defattr(-,root,root,-)
/usr/share/lksctp-tools/checksctp.c
/usr/share/lksctp-tools/sctp_bind.c
/usr/share/lksctp-tools/sctp_darn.c
/usr/share/lksctp-tools/sctp_darn.h
/usr/share/lksctp-tools/sctp_load_libs.c
/usr/share/lksctp-tools/sctp_socket.c
/usr/share/lksctp-tools/sctp_socket.h
/usr/share/lksctp-tools/sctp_sockopt.c
/usr/share/lksctp-tools/sctp_status.c
/usr/share/lksctp-tools/sctp_test.c

%files dev
%defattr(-,root,root,-)
/usr/include/netinet/sctp.h
/usr/lib64/libsctp.so
/usr/lib64/pkgconfig/libsctp.pc
/usr/share/man/man3/sctp_bindx.3
/usr/share/man/man3/sctp_connectx.3
/usr/share/man/man3/sctp_getladdrs.3
/usr/share/man/man3/sctp_getpaddrs.3
/usr/share/man/man3/sctp_opt_info.3
/usr/share/man/man3/sctp_peeloff.3
/usr/share/man/man3/sctp_recvmsg.3
/usr/share/man/man3/sctp_recvv.3
/usr/share/man/man3/sctp_send.3
/usr/share/man/man3/sctp_sendmsg.3
/usr/share/man/man3/sctp_sendv.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsctp.so.1
/usr/lib64/libsctp.so.1.0.18
/usr/lib64/lksctp-tools/libwithsctp.so
/usr/lib64/lksctp-tools/libwithsctp.so.1
/usr/lib64/lksctp-tools/libwithsctp.so.1.0.18

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lksctp-tools/923576601c6fce213eacfa2c860643114a5bf356
/usr/share/package-licenses/lksctp-tools/faa78032a41c2bfe6bfd1df72ccd1bb7ab4f7a10

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/sctp.7
