#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lksctp-tools
Version  : 1.0.16
Release  : 5
URL      : https://sourceforge.net/projects/lksctp/files/lksctp-tools/lksctp-tools-1.0.16.tar.gz
Source0  : https://sourceforge.net/projects/lksctp/files/lksctp-tools/lksctp-tools-1.0.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: lksctp-tools-bin = %{version}-%{release}
Requires: lksctp-tools-data = %{version}-%{release}
Requires: lksctp-tools-lib = %{version}-%{release}
Requires: lksctp-tools-license = %{version}-%{release}
Requires: lksctp-tools-man = %{version}-%{release}

%description
This is the lksctp-tools package for Linux Kernel SCTP Reference
Implementation.

%package bin
Summary: bin components for the lksctp-tools package.
Group: Binaries
Requires: lksctp-tools-data = %{version}-%{release}
Requires: lksctp-tools-license = %{version}-%{release}
Requires: lksctp-tools-man = %{version}-%{release}

%description bin
bin components for the lksctp-tools package.


%package data
Summary: data components for the lksctp-tools package.
Group: Data

%description data
data components for the lksctp-tools package.


%package dev
Summary: dev components for the lksctp-tools package.
Group: Development
Requires: lksctp-tools-lib = %{version}-%{release}
Requires: lksctp-tools-bin = %{version}-%{release}
Requires: lksctp-tools-data = %{version}-%{release}
Provides: lksctp-tools-devel = %{version}-%{release}

%description dev
dev components for the lksctp-tools package.


%package lib
Summary: lib components for the lksctp-tools package.
Group: Libraries
Requires: lksctp-tools-data = %{version}-%{release}
Requires: lksctp-tools-license = %{version}-%{release}

%description lib
lib components for the lksctp-tools package.


%package license
Summary: license components for the lksctp-tools package.
Group: Default

%description license
license components for the lksctp-tools package.


%package man
Summary: man components for the lksctp-tools package.
Group: Default

%description man
man components for the lksctp-tools package.


%prep
%setup -q -n lksctp-tools-1.0.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545263468
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1545263468
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lksctp-tools
cp COPYING %{buildroot}/usr/share/package-licenses/lksctp-tools/COPYING
cp COPYING.lib %{buildroot}/usr/share/package-licenses/lksctp-tools/COPYING.lib
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/checksctp
/usr/bin/sctp_darn
/usr/bin/sctp_status
/usr/bin/sctp_test
/usr/bin/withsctp

%files data
%defattr(-,root,root,-)
/usr/share/lksctp-tools/checksctp.c
/usr/share/lksctp-tools/sctp_bind.c
/usr/share/lksctp-tools/sctp_darn.c
/usr/share/lksctp-tools/sctp_darn.h
/usr/share/lksctp-tools/sctp_load_libs.c
/usr/share/lksctp-tools/sctp_socket.c
/usr/share/lksctp-tools/sctp_socket.h
/usr/share/lksctp-tools/sctp_sockopt.c
/usr/share/lksctp-tools/sctp_status.c
/usr/share/lksctp-tools/sctp_test.c

%files dev
%defattr(-,root,root,-)
/usr/include/netinet/sctp.h
/usr/lib64/libsctp.so
/usr/share/man/man3/sctp_bindx.3
/usr/share/man/man3/sctp_connectx.3
/usr/share/man/man3/sctp_getladdrs.3
/usr/share/man/man3/sctp_getpaddrs.3
/usr/share/man/man3/sctp_opt_info.3
/usr/share/man/man3/sctp_peeloff.3
/usr/share/man/man3/sctp_recvmsg.3
/usr/share/man/man3/sctp_send.3
/usr/share/man/man3/sctp_sendmsg.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsctp.so.1
/usr/lib64/libsctp.so.1.0.16
/usr/lib64/lksctp-tools/libwithsctp.so
/usr/lib64/lksctp-tools/libwithsctp.so.1
/usr/lib64/lksctp-tools/libwithsctp.so.1.0.16

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lksctp-tools/COPYING
/usr/share/package-licenses/lksctp-tools/COPYING.lib

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/sctp.7
